name: PHP

on:
    pull_request:
        branches: [main]

jobs:
    build:
        name: Coding Standards And Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring, xml, bcmath
                  coverage: none

            - name: Install dependencies
              run: composer install

            - name: Run standards check
              run: composer run standards:check

            - name: Run tests
              run: composer run tests
